

include $(GOROOT)/src/Make.inc

#CGO_LDFLAGS=  -lm
DEPS=
TARG=synstation
GOFILES=constants.go\
init.go\
emitter.go\
channels.go\
connection.go\
mobile.go\
synstation.go\
powerC.go\
powerControl.go\
trace.go\
physReceiverBase.go\
meanStruct.go\
FadingGen.go\
agent.go\
RBSchedule2.go\
ChHop2.go\
constantV.go\
RBSchedule4.go\
RBSchedule1.go\
RBSchedule5.go\
ChHop1.go\
icim.go\
ChHop3.go\
ChanReceiver.go\
shadowing.go\
RBScheduleSDMA.go


include $(GOROOT)/src/Make.pkg


