

include $(GOROOT)/src/Make.inc

#CGO_LDFLAGS=  -lm
DEPS=
TARG=synstation
GOFILES=constants.go\
init.go\
emitter.go\
channels.go\
connection.go\
mobile.go\
synstation.go\
physReceiverSectored.go\
powerC.go\
trace.go\
physReceiver.go\
meanStruct.go\
FadingGen.go\
agent.go


include $(GOROOT)/src/Make.pkg


