

include $(GOROOT)/src/Make.inc

#CGO_LDFLAGS=  -lm
DEPS=sselib
TARG=synstation
GOFILES=constants.go\
init.go\
emitter.go\
channels.go\
connection.go\
mobile.go\
synstation.go\
physReceiverSectored.go\
powerC.go\
trace.go\
physReceiver.go\
fastfading.go\


include $(GOROOT)/src/Make.pkg


