

include $(GOROOT)/src/Make.inc

#CGO_LDFLAGS=  -lm
DEPS=
TARG=compMatrix
GOFILES=dense_arithmetic.go\
  densebench_test.go\
  dense_decomp.go\
  dense.go\
  dense_test.go\
  util.go\
  dense_basic.go\
  dense_data.go\
  dense_eigen.go\
  dense_svd.go\
  error.go\
  arithmetic.go\
  matrix.go

include $(GOROOT)/src/Make.pkg


